adjust workflows

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,39 +11,25 @@ jobs:
     env:
       CI: true
 
-    strategy:
-      matrix:
-        os: [ubuntu-latest, windows-latest, macOS-latest]
-        node: [13.x, 12.x, 10.x]
-        exclude:
-          # On Windows, run tests with only the latest environments.
-          - os: windows-latest
-            node: 10.x
-          - os: windows-latest
-            node: 13.x
-          # On macOS, run tests with only the latest environments.
-          - os: macOS-latest
-            node: 10.x
-          - os: macOS-latest
-            node: 13.x
-
-    runs-on: ${{ matrix.os }}
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
         with:
           fetch-depth: 1
       - uses: actions/setup-node@v1
         with:
-          node-version: ${{ matrix.node }}
+          node-version: '12.x'
       - run: yarn install --frozen-lockfile --ignore-optional --non-interactive --silent
       - run: node --expose-gc node_modules/jest/bin/jest --forceExit --bail --colors --logHeapUsage --maxWorkers=2 --ci
 
       - name: Upload coverage to Codecov
         # https://github.com/codecov/codecov-bash/blob/1044b7a243e0ea0c05ed43c2acd8b7bb7cef340c/codecov#L158
-        run: npx codecov
-          -f "./coverage/coverage-final.json"
-          -y "./.codecov.yml"
-          -b ${{ github.head_ref }}
-          -c ${{ github.event.after }}
+        run: bash <(curl -s https://codecov.io/bash)
+          -f ./coverage/coverage-final.json
+          -F client
+          -P ${{ github.event.number }}
+          -B ${{ github.head_ref }}
+          -C ${{ github.event.after }}
+          -Z || echo 'Codecov upload failed'
         env:
           CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
